project_id = "cldpflpfyoalxxioaqab"

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.create-super-like-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-subscription-checkout]
verify_jwt = true

[functions.create-read-receipts-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.update-ghosting-stats]
verify_jwt = false

[functions.send-conversation-nudges]
verify_jwt = false